/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.FrontLiner;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "FrontLiner", description = "the FrontLiner API")
public interface FrontLinerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /frontliners : Create a frontliner
     * Add a new frontliner.
     *
     * @param frontLiner  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createFrontliner",
        summary = "Create a frontliner",
        description = "Add a new frontliner.",
        tags = { "FrontLiner" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FrontLiner.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/frontliners",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FrontLiner> createFrontliner(
        @Parameter(name = "FrontLiner", description = "", required = true) @Valid @RequestBody FrontLiner frontLiner
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"facebookAccount\" : \"facebookAccount\", \"contact\" : \"contact\", \"completeName\" : \"completeName\", \"frontLinerId\" : 0, \"email\" : \"email\", \"frontLinerCategoryId\" : 6 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /frontliners : Get all frontliners
     * Retrieve a list of frontliners.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllFrontliners",
        summary = "Get all frontliners",
        description = "Retrieve a list of frontliners.",
        tags = { "FrontLiner" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FrontLiner.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/frontliners",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<FrontLiner>> getAllFrontliners(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"facebookAccount\" : \"facebookAccount\", \"contact\" : \"contact\", \"completeName\" : \"completeName\", \"frontLinerId\" : 0, \"email\" : \"email\", \"frontLinerCategoryId\" : 6 }, { \"facebookAccount\" : \"facebookAccount\", \"contact\" : \"contact\", \"completeName\" : \"completeName\", \"frontLinerId\" : 0, \"email\" : \"email\", \"frontLinerCategoryId\" : 6 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
