/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.FrontLinerCategory;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "FrontLinerCategory", description = "the FrontLinerCategory API")
public interface FrontLinerCategoryApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /frontliner-categories : Create a frontliner category
     * Add a new frontliner category.
     *
     * @param frontLinerCategory  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createFrontlinerCategory",
        summary = "Create a frontliner category",
        description = "Add a new frontliner category.",
        tags = { "FrontLinerCategory" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FrontLinerCategory.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/frontliner-categories",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FrontLinerCategory> createFrontlinerCategory(
        @Parameter(name = "FrontLinerCategory", description = "", required = true) @Valid @RequestBody FrontLinerCategory frontLinerCategory
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"jobDescription\" : \"jobDescription\", \"categoryName\" : \"categoryName\", \"categoryId\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /frontliner-categories : Get all frontliner categories
     * Retrieve a list of frontliner categories.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllFrontlinerCategories",
        summary = "Get all frontliner categories",
        description = "Retrieve a list of frontliner categories.",
        tags = { "FrontLinerCategory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FrontLinerCategory.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/frontliner-categories",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<FrontLinerCategory>> getAllFrontlinerCategories(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"jobDescription\" : \"jobDescription\", \"categoryName\" : \"categoryName\", \"categoryId\" : 0 }, { \"jobDescription\" : \"jobDescription\", \"categoryName\" : \"categoryName\", \"categoryId\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
