/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.Registration;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "Registration", description = "the Registration API")
public interface RegistrationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /registrations : Create a registration
     * Add a new registration.
     *
     * @param registration  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createRegistration",
        summary = "Create a registration",
        description = "Add a new registration.",
        tags = { "Registration" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Registration.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/registrations",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Registration> createRegistration(
        @Parameter(name = "Registration", description = "", required = true) @Valid @RequestBody Registration registration
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"dob\" : \"2000-01-23\", \"contact\" : \"contact\", \"registrationId\" : 0, \"middleName\" : \"middleName\", \"email\" : \"email\", \"username\" : \"username\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /registrations : Get all registrations
     * Retrieve a list of registrations.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllRegistrations",
        summary = "Get all registrations",
        description = "Retrieve a list of registrations.",
        tags = { "Registration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Registration.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/registrations",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Registration>> getAllRegistrations(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"dob\" : \"2000-01-23\", \"contact\" : \"contact\", \"registrationId\" : 0, \"middleName\" : \"middleName\", \"email\" : \"email\", \"username\" : \"username\", \"status\" : \"status\" }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"password\" : \"password\", \"dob\" : \"2000-01-23\", \"contact\" : \"contact\", \"registrationId\" : 0, \"middleName\" : \"middleName\", \"email\" : \"email\", \"username\" : \"username\", \"status\" : \"status\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
