/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.Student;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "Student", description = "the Student API")
public interface StudentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /students : Create a student
     * Add a new student.
     *
     * @param student  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createStudent",
        summary = "Create a student",
        description = "Add a new student.",
        tags = { "Student" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/students",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Student> createStudent(
        @Parameter(name = "Student", description = "", required = true) @Valid @RequestBody Student student
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"studentId\" : 0, \"gender\" : \"gender\", \"contactInfo\" : \"contactInfo\", \"dob\" : \"2000-01-23\", \"rollNumber\" : 6, \"fullName\" : \"fullName\", \"className\" : \"className\", \"section\" : \"section\", \"vaccinated\" : true, \"vaccinationRecordId\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /students : Get all students
     * Retrieve a list of students.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllStudents",
        summary = "Get all students",
        description = "Retrieve a list of students.",
        tags = { "Student" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Student.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/students",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Student>> getAllStudents(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"studentId\" : 0, \"gender\" : \"gender\", \"contactInfo\" : \"contactInfo\", \"dob\" : \"2000-01-23\", \"rollNumber\" : 6, \"fullName\" : \"fullName\", \"className\" : \"className\", \"section\" : \"section\", \"vaccinated\" : true, \"vaccinationRecordId\" : 1 }, { \"studentId\" : 0, \"gender\" : \"gender\", \"contactInfo\" : \"contactInfo\", \"dob\" : \"2000-01-23\", \"rollNumber\" : 6, \"fullName\" : \"fullName\", \"className\" : \"className\", \"section\" : \"section\", \"vaccinated\" : true, \"vaccinationRecordId\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
