/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.VaccinationSchedule;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "VaccinationSchedule", description = "the VaccinationSchedule API")
public interface VaccinationScheduleApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /vaccination-schedules : Create a vaccination schedule
     * Add a new vaccination schedule.
     *
     * @param vaccinationSchedule  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createVaccinationSchedule",
        summary = "Create a vaccination schedule",
        description = "Add a new vaccination schedule.",
        tags = { "VaccinationSchedule" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VaccinationSchedule.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/vaccination-schedules",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<VaccinationSchedule> createVaccinationSchedule(
        @Parameter(name = "VaccinationSchedule", description = "", required = true) @Valid @RequestBody VaccinationSchedule vaccinationSchedule
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"2000-01-23\", \"timeEnd\" : \"timeEnd\", \"timeStart\" : \"timeStart\", \"vaccinationCenterId\" : 6, \"slotsAvailable\" : 5, \"vaccineInfoId\" : 1, \"scheduleId\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /vaccination-schedules : Get all vaccination schedules
     * Retrieve a list of vaccination schedules.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllVaccinationSchedules",
        summary = "Get all vaccination schedules",
        description = "Retrieve a list of vaccination schedules.",
        tags = { "VaccinationSchedule" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VaccinationSchedule.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/vaccination-schedules",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<VaccinationSchedule>> getAllVaccinationSchedules(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"2000-01-23\", \"timeEnd\" : \"timeEnd\", \"timeStart\" : \"timeStart\", \"vaccinationCenterId\" : 6, \"slotsAvailable\" : 5, \"vaccineInfoId\" : 1, \"scheduleId\" : 0 }, { \"date\" : \"2000-01-23\", \"timeEnd\" : \"timeEnd\", \"timeStart\" : \"timeStart\", \"vaccinationCenterId\" : 6, \"slotsAvailable\" : 5, \"vaccineInfoId\" : 1, \"scheduleId\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
