/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.VaccinationRecord;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "VaccinationRecord", description = "the VaccinationRecord API")
public interface VaccinationRecordApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /vaccination-records : Create a vaccination record
     * Add a new vaccination record.
     *
     * @param vaccinationRecord  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createVaccinationRecord",
        summary = "Create a vaccination record",
        description = "Add a new vaccination record.",
        tags = { "VaccinationRecord" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VaccinationRecord.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/vaccination-records",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<VaccinationRecord> createVaccinationRecord(
        @Parameter(name = "VaccinationRecord", description = "", required = true) @Valid @RequestBody VaccinationRecord vaccinationRecord
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"recordId\" : 0, \"boosterDoseDate\" : \"2000-01-23\", \"firstDoseDate\" : \"2000-01-23\", \"vaccineBooster\" : true, \"secondDoseDate\" : \"2000-01-23\", \"registrationId\" : 6, \"doctorComments\" : \"doctorComments\", \"vaccineInfoId\" : 1, \"frontLinerId\" : 5, \"remarks\" : \"remarks\", \"patientFeelings\" : \"patientFeelings\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /vaccination-records : Get all vaccination records
     * Retrieve a list of vaccination records.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllVaccinationRecords",
        summary = "Get all vaccination records",
        description = "Retrieve a list of vaccination records.",
        tags = { "VaccinationRecord" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VaccinationRecord.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/vaccination-records",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<VaccinationRecord>> getAllVaccinationRecords(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"recordId\" : 0, \"boosterDoseDate\" : \"2000-01-23\", \"firstDoseDate\" : \"2000-01-23\", \"vaccineBooster\" : true, \"secondDoseDate\" : \"2000-01-23\", \"registrationId\" : 6, \"doctorComments\" : \"doctorComments\", \"vaccineInfoId\" : 1, \"frontLinerId\" : 5, \"remarks\" : \"remarks\", \"patientFeelings\" : \"patientFeelings\" }, { \"recordId\" : 0, \"boosterDoseDate\" : \"2000-01-23\", \"firstDoseDate\" : \"2000-01-23\", \"vaccineBooster\" : true, \"secondDoseDate\" : \"2000-01-23\", \"registrationId\" : 6, \"doctorComments\" : \"doctorComments\", \"vaccineInfoId\" : 1, \"frontLinerId\" : 5, \"remarks\" : \"remarks\", \"patientFeelings\" : \"patientFeelings\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
