/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schoolvaccination.api;

import com.schoolvaccination.model.VaccinationCenter;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-28T23:54:16.732248500+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "VaccinationCenter", description = "the VaccinationCenter API")
public interface VaccinationCenterApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /vaccination-centers : Create a vaccination center
     * Add a new vaccination center.
     *
     * @param vaccinationCenter  (required)
     * @return Created successfully (status code 201)
     */
    @Operation(
        operationId = "createVaccinationCenter",
        summary = "Create a vaccination center",
        description = "Add a new vaccination center.",
        tags = { "VaccinationCenter" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VaccinationCenter.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/vaccination-centers",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<VaccinationCenter> createVaccinationCenter(
        @Parameter(name = "VaccinationCenter", description = "", required = true) @Valid @RequestBody VaccinationCenter vaccinationCenter
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"centerId\" : 0, \"vaccinationCenter\" : \"vaccinationCenter\", \"address\" : \"address\", \"latitude\" : 1.4658129805029452, \"contactNumber\" : \"contactNumber\", \"longitude\" : 6.027456183070403, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /vaccination-centers : Get all vaccination centers
     * Retrieve a list of vaccination centers.
     *
     * @return Successful retrieval (status code 200)
     */
    @Operation(
        operationId = "getAllVaccinationCenters",
        summary = "Get all vaccination centers",
        description = "Retrieve a list of vaccination centers.",
        tags = { "VaccinationCenter" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful retrieval", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VaccinationCenter.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/vaccination-centers",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<VaccinationCenter>> getAllVaccinationCenters(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"centerId\" : 0, \"vaccinationCenter\" : \"vaccinationCenter\", \"address\" : \"address\", \"latitude\" : 1.4658129805029452, \"contactNumber\" : \"contactNumber\", \"longitude\" : 6.027456183070403, \"status\" : \"status\" }, { \"centerId\" : 0, \"vaccinationCenter\" : \"vaccinationCenter\", \"address\" : \"address\", \"latitude\" : 1.4658129805029452, \"contactNumber\" : \"contactNumber\", \"longitude\" : 6.027456183070403, \"status\" : \"status\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
